token:
  expiration: 36000009
  secret: user_name

gateway:
  ip: 127.0.0.1

kafka:
  topic:
    order:
      catalog: 'order-catalog'
      sync: 'order-db-sync'

spring:
  kafka:
    consumer:
      group-id: consumer-group-id