
server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}//I:\programming\Spring_Cloud\configurations
        git:
          uri: https://github.com/alska95/SpringCloud_Practice/configurations.git
#          uri: file://I:\programming\Spring_Cloud\configurations
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
